### ISSUE TITLE
include access restriction in showing inventory items. [$this->genlib->superOnly();], 

### ISSUE THREAD

**Issue by Nayr18** [amirsanni/Mini-Inventory-and-Sales-Management-System#13]
the basic level admin can access inventory through url "/items". or just exclude the inventory items from admin role check in main.php

**Comment by amirsanni** [comment]
This depends on your use case. If you want to restrict the access to that module, do it but by default it's not restricted to super admin only?

**Comment by amirsanni** [comment]
Are you saying the module is restricted from view but not in the controller? If that's the case, I'll look into it and do one of the two. Either restrict it to super admin by preventing it from the controller, or make it accessible by enabling it from the view. 

Thanks for that.

**Comment by Nayr18** [comment]
exactly . sorry for my unclear point. Thank you for understanding and thank you for sharing your work :)

**Comment by amirsanni** [comment]
Done. Welcome.
