### ISSUE TITLE
Mobile login issue 

### ISSUE THREAD

**Issue by Nayr18** [amirsanni/Mini-Inventory-and-Sales-Management-System#14]
its just me or what, i can't login using mobile

**Comment by amirsanni** [comment]
What message do you get?

**Comment by Nayr18** [comment]
nothing, it doesn't continue to dashboard.

**Comment by Nayr18** [comment]
just keep authenticating . the backend seems successfully logged in because my browser catched the username and password, but the front end don't

**Comment by Nayr18** [comment]
maybe it's about CI native session ? .

**Comment by amirsanni** [comment]
Where are you testing from? I can log in to the demo from on mobile from my end. Are you sure it's not a browser issue?

**Comment by Nayr18** [comment]
im sorry, ur right .. browser issue

**Comment by Nayr18** [comment]
thank you :)

**Comment by amirsanni** [comment]
Welcome
