### ISSUE TITLE
Transaction search missing customer details 

### ISSUE THREAD

**Issue by deegha** [amirsanni/Mini-Inventory-and-Sales-Management-System#19]
When searching transactions by transactions ids, there is an undefined variable error in customer details area

**Comment by deegha** [comment]
### FIX 

- Add the following attributes to the `transSearch` function select query 

 `transactions.cust_name, transactions.cust_phone, transactions.cust_email`

**Comment by amirsanni** [comment]
Thanks. Will do that.
