### ISSUE TITLE
Floating number with at least 2 digits at quantity field in transactions 

### ISSUE THREAD

**Issue by ciovyalin** [amirsanni/Mini-Inventory-and-Sales-Management-System#20]
I want the unit price to act as per unit and as per kg. (KG or Unit will be specified in description)
So I need the quantity to accept floating numbers that can multiply with the unit price.

**Comment by amirsanni** [comment]
This is for a specific use-case which you should add from your end. You can do this by changing the quantity fields to **text** instead of **number** AND also changing the dataType of those fields in the Database.
