### ISSUE TITLE
How to change date/Time to my local time (GMT +2:00)

### ISSUE THREAD

**Issue by waqasamjad1** [amirsanni/Mini-Inventory-and-Sales-Management-System#24]
I tried to change the time_zone in my sql but that doesn't help. 
Kindly let me fix this.

Thanks in advance

**Comment by amirsanni** [comment]
For the PHP side, Open **application=>config=>config.php** and change the default timezone on line with `$config['time_reference']`. As for MySQL, you might have to check the MySQL manual on how to go about it.
