### ISSUE TITLE
Item Code input method invalid

### ISSUE THREAD

**Issue by DevHunter0101x** [amirsanni/Mini-Inventory-and-Sales-Management-System#26]
URL: https://1410inc.xyz/mini-inventory-and-sales-management-system/transactions
Parameter: Item code
While adding item using the item code it instantly search the item which makes larger item code entry invalid. for example there are items in DB with codes 1 , 12 , 123 , 1234 , 12345
if i want to enter item with code 12345
till the time i enter 12345, it will add item 123 or 1234 instantly. 
Solution: 
Either set time limit to read input so that larger code can be entered and traced easily OR place a button to initiate the search.
waiting for your quick response/fix.

**Comment by amirsanni** [comment]
Understood. That feature was added for barcode scanner and not for manual input, that's why it's done like that. It's not expected and not intuitive for an item's barcode to be scanned and then have the cashier to manually click a button for the item to be added to the transaction. While the button can be added, I believe it defeats the purpose of adding that field which is meant for reading value from a barcode scanner.

**Comment by DevHunter0101x** [comment]
the error remains the same i tried doing it with barcode as well it still detect the 123 item not 1234 
is there anyway that we can set time limit to retrieve code?

**Comment by amirsanni** [comment]
Oh! Ok. It's possible to add a delay of maybe 3-5 seconds. Can you do that? I won't be chanced today. Perhaps tomorrow or next.

**Comment by DevHunter0101x** [comment]
I dont know what file to edit and what specific function code! if you guide me i can do it.

**Comment by amirsanni** [comment]
Should be in `transactions.js`. I'll need to check as well.

**Comment by amirsanni** [comment]
Should be an event handler listening to that particular input. Check the ID of that input and search for it in `transactions.js`.

**Comment by DevHunter0101x** [comment]
got it but how to extend time limit?

**Comment by DevHunter0101x** [comment]
waiting..

**Comment by amirsanni** [comment]
Done. I put a 3sec delay but I think that's too much. Will reduce it to 2 seconds.

**Comment by amirsanni** [comment]
I have changed it to 1.5secs

**Comment by DevHunter0101x** [comment]
its done thanks. good work
