### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by dogungbeje** [amirsanni/Mini-Inventory-and-Sales-Management-System#27]
Unable to login with the email and password provided.
I got "Log in failed. Please check your internet connection and try again later."

My internet connection is very good.

Please check here: http://www.test.motizafarms.com/

**Comment by amirsanni** [comment]
From my check, it's a server configuration issue. Perhaps you should check your server configuration. Did you follow the instruction in the readme? Perhaps you didn't update the .htaccess file in the root directory.

**Comment by dogungbeje** [comment]
Thanks for your prompt response. Here's my configuration:


 - Open __"application/config/config.php"__ and do the same.

if(is_cli()){
    $config['base_url'] = "";
}

else if(stristr($host, "localhost") !== FALSE || (stristr($host, "192.168.") !== FALSE)|| (stristr($host, "127.0.0.") !== FALSE)){
    $config['base_url'] =  $protocol.$host."http://www.test.motizafarms.com/";
}

else{
    $allowed = ['www.motizafarms.com', 'motizafarms.com'];//input all allowed urls here e.g. amirsanni.com, www.practa.ng, smartagapp.com

    $config['base_url'] = in_array($host, $allowed) ? $protocol.$host."http://www.test.motizafarms.com/" : "http://".$_SERVER['HTTP_HOST']."/";
}

================================================================
- Open __"public/js/main.js"__ and do the same.

var appRoot = setAppRoot("http://www.test.motizafarms.com/", "http://www.test.motizafarms.com/");

================================================================
- Open __.htaccess in the root folder__ and change the line with __"mini-inventory-and-sales-management-system"__ to your new folder name.

RewriteEngine On
RewriteBase /test.motizafarms.com

================================================================

Please kindly direct me  the best way forward.

Thank you so much for the beautiful work.

**Comment by amirsanni** [comment]
This line `var appRoot = setAppRoot("http://www.test.motizafarms.com/", "http://www.test.motizafarms.com/");` is wrong. You're to put the name of the app directory and not the full URL. If it is placed in your **html** root directory, the fields will be blank.

The same thing applies here **RewriteBase /test.motizafarms.com**. Leave blank if the app is in the root directory OR put directory name if placed within a directory inside the root directory.

**Comment by wanewi** [comment]
i have the same problem . I try everything but its not working , maybe i m doing something wrong

**Comment by dogungbeje** [comment]
unfortunately, it didn't work. I tried everything but no luck.

The app is sitting at the root directory of a sub domain test.motizafarms.com

**Comment by dogungbeje** [comment]
Amir, I got it to work. Thank you so much. Keep up the good work.

**Comment by wanewi** [comment]
how ?

**Comment by dogungbeje** [comment]
Wanewi, where's your app? root directory or in a folder?

**Comment by dogungbeje** [comment]
- Open __.htaccess

RewriteEngine On
RewriteBase /mini
=====================================

  - Open __"application/config/config.php"

if(is_cli()){
    $config['base_url'] = "";
}

else if(stristr($host, "localhost") !== FALSE || (stristr($host, "192.168.") !== FALSE)|| (stristr($host, "127.0.0.") !== FALSE)){
    $config['base_url'] =  $protocol.$host."/mini/";
}

else{
    $allowed = ['www.yourdomain.com', 'yourdomain.com'];//input all allowed urls here e.g. amirsanni.com, www.practa.ng, smartagapp.com

    $config['base_url'] = in_array($host, $allowed) ? $protocol.$host."/mini/" : "http://".$_SERVER['HTTP_HOST']."/";
}

================================================================

  - Open __"public/js/main.js"__ and do the same.

var appRoot = setAppRoot("mini", "mini");

**Comment by wanewi** [comment]
no still not working i cant log in

**Comment by DevHunter0101x** [comment]
i had this problem too on a perfectly working application. I just cleared my history and browser cache and it worked.

**Comment by wanewi** [comment]
its still say no internet ..... i refresh everything .

**Comment by dogungbeje** [comment]
I think you should try it on live server no localhost

**Comment by amirsanni** [comment]
Hi @wanewi Did you follow the guide in the readme? If yes, can you share a screenshot of the changes you made? This will help in debugging the issue you're having.

**Comment by wanewi** [comment]
That are my files i try on live server i try everything . Thank you guys . 


[File.zip](https://github.com/amirsanni/Mini-Inventory-and-Sales-Management-System/files/1664074/File.zip)

**Comment by amirsanni** [comment]
The files look OK.

1. What error message are you getting?
2. Do you have **mod_rewrite** enabled on your server?
3. Check the **Network** tab of your console and see which URL is handling the log in.
4. What version of PHP are you using?

**Comment by seksan470029** [comment]
I have same problem. I try solve it to long time. Please tell me how to solve it.

![image](https://user-images.githubusercontent.com/35869563/35472834-37d0a610-03a9-11e8-88de-d8ff2b4643c3.png)

**Comment by amirsanni** [comment]
@seksan470029 Be sure everything is properly set up as in the Readme. Also answer the questions I asked. Thanks

**Comment by seksan470029** [comment]
@amirsanni I can fix it successfully.  My problem was caused by me. 
I change value in config->config.php 
from 
$config['language']	= 'english';
to
$config['language']	= 'germany';

I change it back to default (english) then I can login .

thankyou

**Comment by amirsanni** [comment]
Glad to hear that. Welcome
