### ISSUE TITLE
Need Total Price of All inventory items

### ISSUE THREAD

**Issue by DevHunter0101x** [amirsanni/Mini-Inventory-and-Sales-Management-System#29]
in the inventory items i dont see anywhere total price of my inventory stock. i want to know how much is my inventory total worth. 
It will be good if you add a DB query and display price of total Stock. 
sum UNIT PRICE of all inventory items and display its result in Total stock price.

**Comment by amirsanni** [comment]
Where will this sum be displayed? Not a bad idea.

**Comment by DevHunter0101x** [comment]
Somewhere on the inventory management page. A Textlabel displaying total amount of all inventory items on basis of unitprice.
and yes you can also display another label with it that would be total earned on sold items

**Comment by amirsanni** [comment]
Alright. Will add that when chanced. Thanks

**Comment by DevHunter0101x** [comment]
please make it sooner. I have a lot of stock entered in the system and i wanna know its total cost to cumulative automatically.

**Comment by amirsanni** [comment]
Just a second thought. Should this total be the total unit cost of all items OR total unit cost multiplied by the available quantities of all items?

**Comment by amirsanni** [comment]
I did the latter.

Regards

**Comment by DevHunter0101x** [comment]
total unit cost

**Comment by DevHunter0101x** [comment]
i have replaced all these 4 files 
Mini-Inventory-and-Sales-Management-System/application/controllers/
**items.php**

Mini-Inventory-and-Sales-Management-System/application/views/items/
**items.php
itemslisttable.php**

Mini-Inventory-and-Sales-Management-System/application/models/
**item.php**

I am getting this result now ? it is not showing any of the item :/ 
Please hlep

![image](https://user-images.githubusercontent.com/25959652/35444270-ce006682-02cf-11e8-9a21-16dea21ad490.png)

**Comment by amirsanni** [comment]
Lol. Any error in the console? My guess is your version of PHP. I used a PHP 7 syntax in **itemslisttable.php**.

**Comment by DevHunter0101x** [comment]
mm well i was using the same application before changing the files it was working smooth as ice :D 
so what do i need to do now?

**Comment by amirsanni** [comment]
Which version of PHP are you using? Will use a PHP 5 syntax.Don't worry.

**Comment by DevHunter0101x** [comment]
Its Done now. Great work
