### ISSUE TITLE
Total Earned Today invalid

### ISSUE THREAD

**Issue by DevHunter0101x** [amirsanni/Mini-Inventory-and-Sales-Management-System#30]
Total Earned Today: displays wrong total of price earned today. Thats because if we have multiple items in transaction it multiples the total amount with number of items and displays that amount. 
For example. if there is only 1 item in transaction it will add same total price in total earned today. 
but if we have 2 items in transaction it will add ( total price of transaction x 2) in the total earned today
similarly if we have 3 items in transaction it will add ( total price of transaction x 3) in the total earned today
Please fix this error. 
the error is only in top right total earned today: (_____)

**Comment by amirsanni** [comment]
Please check again. It is not wrong. Perhaps I am missing something.

If 3 quantities of an Item is bought, the total amount will be the **unitPrice** of the item multiplied by the quantity. Similar thing will be done for all items in that transaction. 

The addition of the total amount of these items will give us the **Total Amount** of that transaction.

The additional of the **total amount** of all transactions done on a particular day will give us the **total earned** that day.

Hope you understand?

**Comment by DevHunter0101x** [comment]
total transaction amount should be added into total earned today its multiplying the total transcation amount (which is correct in transaction receipt) with the number of items in transaction and then adding in the total earned.

**Comment by DevHunter0101x** [comment]
![image](https://user-images.githubusercontent.com/25959652/35440096-bc306ade-02bf-11e8-9cae-73753354d417.png)

Just as in screenshot the total earned was zero and i did a transaction of two items which total was 111 
hence total earned was 111 but it multiplied it with total number of items and showed 222. 
similarly if we put three , four , five or so on it does multiply the total amount of transaction with total items and then displays total earned which is invalid !

**Comment by DevHunter0101x** [comment]
![image](https://user-images.githubusercontent.com/25959652/35440378-f0f4aeb4-02c0-11e8-9d4c-0a300d01508b.png)

now here see another transaction i did. what it did is multiplied it with total items. we had 222 already earned and now we earned 400 but it is displaying wrong sum of earned. it is multiplying 400 with 4 and adding 1600 in 222 which makes 1822 while it should add only 400 in total earned. ! 
fix it.

**Comment by amirsanni** [comment]
Oh! Guess this happens immediately after a transaction is done, right?

When you refresh the page, does it still show a wrong calculation? This will help in isolating the issue.

**Comment by DevHunter0101x** [comment]
refreshing the page still shows the wrong calculation. 
it is simply multiplying the actual correct calculation with the number of items. 
only this multiplication has to stop

**Comment by DevHunter0101x** [comment]
if we have 1 item and its price is 200 it will multiply total with 1 i.e 200* 1 =200
if we have 4 items and its price each is 200 it will multiply total 800 with 4 i.e 800* 4 =3200 which is wrong

**Comment by amirsanni** [comment]
Will look into it. Thanks

**Comment by DevHunter0101x** [comment]
Its disturbing the whole record on main home dashboard!  Fix it asap kindly

**Comment by amirsanni** [comment]
Fixed
