### ISSUE TITLE
Facing Error on Search. 

### ISSUE THREAD

**Issue by DevHunter0101x** [amirsanni/Mini-Inventory-and-Sales-Management-System#32]
![1](https://user-images.githubusercontent.com/25959652/35635148-51dbcd40-06cf-11e8-8498-0c6d61f2e565.png)

im facing this error while searching anything.
it does perfectly searches the querry but displays this error. i dont know what is it about. ??fix it?

**Comment by amirsanni** [comment]
Add `$data['cum_total'] = $this->item->getItemsCumTotal();` to line 80 in **Controllers=>Search.php**. I will update the script as well.

**Comment by DevHunter0101x** [comment]
![image](https://user-images.githubusercontent.com/25959652/35861278-f2f47e5a-0b68-11e8-8655-8d7a688c69fd.png)

getting this error in transactions search
