### ISSUE TITLE
login failed

### ISSUE THREAD

**Issue by aristaf** [amirsanni/Mini-Inventory-and-Sales-Management-System#35]
i just update the php but still failed

**Comment by amirsanni** [comment]
Any error message?

**Comment by aristaf** [comment]
need to connect to internet. Login failed.

**Comment by kitsoul** [comment]
Log in failed. Please check your internet connection and try again later.

**Comment by kitsoul** [comment]
project is in localhost
Log in failed. Please check your internet connection and try again later.

**Comment by limmazzum** [comment]
![login error](https://user-images.githubusercontent.com/36757535/36584429-9a6ebf08-18b4-11e8-9241-d24a4a69ce0f.PNG)

**Comment by limmazzum** [comment]
![login error](https://user-images.githubusercontent.com/36757535/36584449-b0e42d90-18b4-11e8-81b2-7055cbfe2f91.PNG)

I'm having problem to login to the system. When I enter the username and password, nothing happen. It do not redirect me to the dashboard of the system.

**Comment by amirsanni** [comment]
@kitsoul Any luck? Can you share more information about your setup?

@limmazzum From your screenshot, I think your files are not properly linked. Perhaps a setup issue.

**Comment by elkhariq** [comment]
![error](https://user-images.githubusercontent.com/8565110/37697908-3d115cb8-2d12-11e8-9cf3-35f5ffb34921.png)

There is No controller "Access", are you sure @amirsanni ? how to solve this..?

**Comment by yasinyus** [comment]
are you delete some file? because of that we can't login. we all have same problem when login
"Log in failed. Please check your internet connection and try again later."
Any solution?
Note: I login with email : demo@1410inc.xyz and pass: demopass

**Comment by amirsanni** [comment]
Nothing has changed. Was able to log in just now.

Are you testing on the demo or on your localhost?

**Comment by elkhariq** [comment]
I test on localhost....(there is no "Access" controller in your controller folder below, can you re-upload the folder controller?
![image](https://user-images.githubusercontent.com/8565110/38652556-b03ad208-3e30-11e8-9312-82425435ddec.png)

**Comment by yasinyus** [comment]
i test in localhost

**Comment by Jacoblev** [comment]
some one managed to make the Log in failed. Please check your internet connection and try again later. to work?

**Comment by raivtash** [comment]
same problem with my localhost...

**Comment by sahilbadyal** [comment]
Check your apache conf. Make sure your directory has 
AllowOverride All instead of AllowOverride None

`<Directory "/var/www/html">
    #
    # Possible values for the Options directive are "None", "All",
    # or any combination of:
    #   Indexes Includes FollowSymLinks SymLinksifOwnerMatch ExecCGI MultiViews
    #
    # Note that "MultiViews" must be named *explicitly* --- "Options All"
    # doesn't give it to you.
    #
    # The Options directive is both complicated and important.  Please see
    # http://httpd.apache.org/docs/2.4/mod/core.html#options
    # for more information.
    #
    Options Indexes FollowSymLinks

    #
    # AllowOverride controls what directives may be placed in .htaccess files.
    # It can be "All", "None", or any combination of the keywords:
    #   Options FileInfo AuthConfig Limit
    #
    AllowOverride All

    #
    # Controls who can get stuff from this server.
    #
    Require `

**Comment by dj0le** [comment]
my AllowOverride is set to All but I still get the "Log in failed. Please check your internet connection and try again later." error message when attempting to connect to localhost

**Comment by raphaeleli** [comment]
need help with the log in side

**Comment by phillipfrancia** [comment]
Can't login

**Comment by evilnohds** [comment]
Same problem here too.

**Comment by amirsanni** [comment]
Few things could cause this issue.
1. The directory name is different from what you have in **application=>config=>config.php**.
2. Directory name is not properly set in **main.js**.
3. You don't have mod_rewrite enabled.

Checking the error message in your browser console or the network tab will be helpful.

Share what you have in your console.

Also ensure you follow the setup instruction in the readme.

**Comment by svlasin** [comment]
what is the solution to the login error I am trying with the php 7.0 and with the php 5.6 but I do not get the error is the same
any solution please

**Comment by amirsanni** [comment]
Check your console for the error message. If it is a page not found error, then it's either mod_rewrite is not enabled or you don't have the correct directory name in the .htaccess file in the root directory.

**Comment by phemieny7** [comment]
Please who has been able to login, please share a video on youtube for us to see how it works

**Comment by phemieny7** [comment]
> Check your console for the error message. If it is a page not found error, then it's either mod_rewrite is not enabled or you don't have the correct directory name in the .htaccess file in the root directory.

i leave the file as it was been downloaded.

**Comment by stanyjude** [comment]
I too had the same issue and enabling mod_rewrite fixed it for me.

On Ubuntu terminal please run the following commands:
sudo a2enmod rewrite
sudo /etc/init.d/apache2 restart

**Comment by davipires** [comment]
Não é possivel logar, todos os pré-requisitos foram validados.

**Comment by akhilkumar332** [comment]
Same issue, Any help
![image](https://user-images.githubusercontent.com/25744542/50057639-3c008c80-0193-11e9-8e45-ae75d77c5fbe.png)

**Comment by uhexos** [comment]
> I too had the same issue and enabling mod_rewrite fixed it for me.
> 
> On Ubuntu terminal please run the following commands:
> sudo a2enmod rewrite
> sudo /etc/init.d/apache2 restart

didnt work for me

**Comment by uhexos** [comment]
> Check your console for the error message. If it is a page not found error, then it's either mod_rewrite is not enabled or you don't have the correct directory name in the .htaccess file in the root directory.

@amirsanni please i have turned on mod_rewrite and have double checked the .htaccess file and still i cannot sign in

**Comment by akhilkumar332** [comment]
https://github.com/amirsanni/Mini-Inventory-and-Sales-Management-System/issues/35#issuecomment-447667358
Strange, in localhost  this application is not working but when configured online on my server it's working fine.

For those this application is not working, try to upload it online and then try again.

**Comment by BryanCoronelTapia** [comment]
I got it....
First make sure that you have enabled rewrite mod, and in addition change the mod to production in principal index.php.
![screenshot from 2019-03-05 14-36-01](https://user-images.githubusercontent.com/45852846/53832684-cbc50400-3f54-11e9-9162-9bc3960124a2.png)

**Comment by uhexos** [comment]
> I got it....
> First make sure that you have enabled rewrite mod, and in addition change the mod to production in principal index.php.
> ![screenshot from 2019-03-05 14-36-01](https://user-images.githubusercontent.com/45852846/53832684-cbc50400-3f54-11e9-9162-9bc3960124a2.png)

could you explain what you mean by change the mod ?

**Comment by BryanCoronelTapia** [comment]
Here I have changed development to production
`define('ENVIRONMENT', isset($_SERVER['CI_ENV']) ? $_SERVER['CI_ENV'] : 'development');`

**Comment by sddennerr** [comment]
Instead of Localhost Use 127.0.0.1. It worked for me.

**Comment by Arsiirasheed** [comment]
just do this ...
edit /etc/apache2/apache2.conf file 
and make change to directory as follow
`<Directory /var/www/>
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>`
save file and restart apache 
hope it works
