### ISSUE TITLE
Currency

### ISSUE THREAD

**Issue by defarijnr** [amirsanni/Mini-Inventory-and-Sales-Management-System#36]
Hi awesome project you have. Where are the settings for currency?

**Comment by amirsanni** [comment]
Unfortunately, there is currently no setting for that at the moment. It is planned, however.

**Comment by defarijnr** [comment]
I see. How can I find the ₦ symbol in the system? Or maybe change it if possible

**Comment by amirsanni** [comment]
It's hardcoded. &#8358;

**Comment by amirsanni** [comment]
"&#8358;"

**Comment by meetsonpar** [comment]
the coding of that hard coded symbol is in which page ?

**Comment by aminemshady2080** [comment]
yes use the find & replace tool in your editor to find hardcoded #8358; and replace it with your current symbol
that how i did it
