### ISSUE TITLE
Php error

### ISSUE THREAD

**Issue by meetsonpar** [amirsanni/Mini-Inventory-and-Sales-Management-System#37]
hey sorry but i cant able to run this project always getting error 

Parse error: syntax error, unexpected '[' in C:\xampp\htdocs\mini\application\config\config.php on line 38

i did those changes which was mentioned ! still not working out !

**Comment by amirsanni** [comment]
Are you sure your version of PHP supports array declaration with []?

**Comment by meetsonpar** [comment]
so the version of PHP is the problem , let me install XAMPP with newest version of PHP 7.2.2, then let you know about the progress !

**Comment by amirsanni** [comment]
Welcome.
