### ISSUE TITLE
how to add in expenditures/spendings/outgoing transactions

### ISSUE THREAD

**Issue by aminemshady2080** [amirsanni/Mini-Inventory-and-Sales-Management-System#38]
Hi Amir thx for the project again it does only wonders to help me in my projects to
but how can go by adding expenditures/spendings/outgoing transactions functionalities

coz this project's file are super nested 

and how to fix transaction reciept being printed and having to much padding on side that causes to not fill on print paper.

thx again

**Comment by amirsanni** [comment]
- Adding new features should be straightforward if you understand CodeIgniter or how MVC works basically. I am afraid you'll have to add that on your own as I have very little time at the moment.

- For printing, the printing feature was targeted at Thermal printers. You can also easily modify it to suit your needs (paper size etc.).

**Comment by aminemshady2080** [comment]
thx for the reply man
will digg deeper into it
thx again ur codes rocks

**Comment by amirsanni** [comment]
Glad to hear that. You're welcome.
