### ISSUE TITLE
when i install this program,an error happened

### ISSUE THREAD

**Issue by xiutuo** [amirsanni/Mini-Inventory-and-Sales-Management-System#39]
install this program,we got error :
A Database Error Occurred

SQLSTATE[HY000] [2002] No such file or directory

Filename: controllers/Home.php

Line Number: 13

============
I had modified these files(even default ,its did not works),any tips?,thanks
public/js/main.js
application/config/config.php
application/config/database.php
.htaccess

**Comment by amirsanni** [comment]
Did you confirm that the file exists?
