### ISSUE TITLE
Need to use discount in price not percentage

### ISSUE THREAD

**Issue by DevHunter0101x** [amirsanni/Mini-Inventory-and-Sales-Management-System#41]
I want to add discount in fix price count i.e 100 or 200 i dont want it to be in percentage % 
can you please make the changing?

![image](https://user-images.githubusercontent.com/25959652/39662413-7e701fa6-507a-11e8-8356-596a2de5cf4d.png)

later the totaly amount before discount should also be printed on reciept also

![image](https://user-images.githubusercontent.com/25959652/39662441-d8f22118-507a-11e8-9c35-1aed3bf68000.png)

**Comment by amirsanni** [comment]
Will try to add this feature. The user will be able to decide whether to set it in percentage or fixed price.

**Comment by DevHunter0101x** [comment]
Yes, thanks add it Asap please.

**Comment by DevHunter0101x** [comment]
@amirsanni after adding the function of decide whether to set it in percentage or fixed price please show the totaly amount before discount on reciept also

**Comment by amirsanni** [comment]
Done

**Comment by DevHunter0101x** [comment]
changed all files accordingly and discount value function is not working at all? @amirsanni
