### ISSUE TITLE
Display Barcode (item code) along with item on Transaction

### ISSUE THREAD

**Issue by DevHunter0101x** [amirsanni/Mini-Inventory-and-Sales-Management-System#44]
if we manually search for any item using the dropdown list (incase we are not using a barcode scanner) 
The barcode of respective searched item should also be displayed , you can place the item code in item code field or make a new field for it. 

![image](https://user-images.githubusercontent.com/25959652/40279065-d72d1aea-5c55-11e8-888c-b84f52865bcc.png)

**Comment by DevHunter0101x** [comment]
@amirsanni  need your attention

**Comment by amirsanni** [comment]
Not sure the importance of this.

**Comment by amirsanni** [comment]
Feature will be included on next update.

**Comment by Ashwin-Kapes** [comment]
How this barcode scanner is working? Do I have to just connect my Barcode reader and it will detect?
