### ISSUE TITLE
Error: Undefined class constant 'MYSQL_ATTR_INIT_COMMAND'

### ISSUE THREAD

**Issue by raivtash** [amirsanni/Mini-Inventory-and-Sales-Management-System#46]
I try this under my fedora 28 and got the following error. I changed the folder name to "inventory". Thank you!

An uncaught Exception was encountered
Type: Error

Message: Undefined class constant 'MYSQL_ATTR_INIT_COMMAND'

Filename: /var/www/html/inventory/system/database/drivers/pdo/subdrivers/pdo_mysql_driver.php

Line Number: 145

Backtrace:

File: /var/www/html/inventory/application/controllers/Home.php
Line: 13
Function: __construct

File: /var/www/html/inventory/index.php
Line: 315
Function: require_once

**Comment by amirsanni** [comment]
Ensure you have the PDO MYSQL Driver enabled in your PHP.

**Comment by raivtash** [comment]
I am not sure, but I think the driver was enabled. I also tried it on a freshly installed debian stretch machine. And now the error is like the following. I tried a few fixes I found online but none worked so far. Thank you!


A Database Error Occurred

SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)

Filename: controllers/Home.php

Line Number: 13

**Comment by amirsanni** [comment]
This is obviously a DB log in issue. Ensure you put the correct credentials of your database in Application/config/database.php

**Comment by raivtash** [comment]
yes, this problem solved by adding correct credentials. but now I have same issue as #17. 

Log in failed. Please check your internet connection and try again later.

My php is:
PHP 7.0.27-0+deb9u1 (cli) 

Thank you again for your help.

**Comment by raivtash** [comment]
![screenshot from 2018-05-29 13-46-42](https://user-images.githubusercontent.com/3376883/40681606-d4d233dc-6346-11e8-9b81-488058f84ac4.png)
![screenshot from 2018-05-29 13-37-34](https://user-images.githubusercontent.com/3376883/40681611-d8cd534a-6346-11e8-9769-99bc1b3119b4.png)

also, here is my inventory.conf in /etc/apache2/sites-enabled/

<VirtualHost *:80>
    <Directory /var/www/inventory/>
        Options Indexes FollowSymlinks Multiviews
        AllowOverride None
        Require all granted
    </Directory>
    DocumentRoot /var/www/inventory
    ServerAdmin admin@inventory.localhost
    ServerName inventory.local
    ServerAlias www.inventory.local
    ErrorLog ${APACHE_LOG_DIR}/inventory-error.log
    CustomLog ${APACHE_LOG_DIR}/inventory-access.log combined
</VirtualHost>

**Comment by amirsanni** [comment]
Sorry, I don't know how you were able to achieve the **inventory.local** URL but I am almost certain the issue is connected to that.

Did it work when you hardcoded the base_url?

Don't know much about your setup, so there is little help I can offer.

**Comment by chamba37** [comment]
![error1](https://user-images.githubusercontent.com/64771728/80946164-5c28ef80-8d78-11ea-87c2-da62d2f286e1.PNG)

error in login page

**Comment by chamba37** [comment]
any assistance please
