### ISSUE TITLE
add date 

### ISSUE THREAD

**Issue by arieljosue** [amirsanni/Mini-Inventory-and-Sales-Management-System#47]
I wanted to manually add the date of the transaction. How?

**Comment by arieljosue** [comment]
awesome thank you. can you tell me which script to edit for it? i'm new to codeigniter and I would really appreciate it if you can tell me

**Comment by amirsanni** [comment]
Application=>Controllers=>Transactions.php. **function nso_()**

**Comment by arieljosue** [comment]
awesome thank you!

**Comment by amirsanni** [comment]
Did you do what I said initially? You'll need to make some modifications. Add a field on the client side for getting transaction date, send the input data to the server side, and use that data as transaction date on the server side/dB.

**Comment by arieljosue** [comment]
Hi amir. Sorry for the late reply. May I know where the can I remove the default value of transdate?

**Comment by arieljosue** [comment]
I have done the latter but the value inserted was always current?

**Comment by arieljosue** [comment]
https://imgur.com/a/7EIZIB8

**Comment by amirsanni** [comment]
Open **application=>model=>transaction.php**, function *add*, the transaction date is set on the line with **$this->db->platform() == "sqlite3" ? $this->db->set('transDate', "datetime('now')", FALSE) : $this->db->set('transDate', "NOW()", FALSE);**

You can remove/comment that line and have the transaction date sent to that function by the calling function and then include it in the $data array in function *add*. Note that the key must the column name in the table, in this case **transDate**.

**Comment by arieljosue** [comment]
Hi, I've done this from what I understand. Am I doing it right?

model --------------------------------------------------------
<img src="https://i.imgur.com/XlBvMh9.png">

view --------------------------------------------------------
<img src="https://i.imgur.com/Hw0aUJc.png">

controller --------------------------------------------------------
<img src="https://i.imgur.com/hzegp9I.png">

**Comment by arieljosue** [comment]
I have an error "Oops! Bug? Unable to process your request. Please try again or report error"
 <img src="https://i.imgur.com/HSWQ64n.png">

**Comment by amirsanni** [comment]
1. Check what the error is on your browser console.
2. Did you send transDate from the client-side (JavaScript)?
