### ISSUE TITLE
Type: Exception

### ISSUE THREAD

**Issue by r3klaw** [amirsanni/Mini-Inventory-and-Sales-Management-System#56]
how do i get past this error:
`An uncaught Exception was encountered
Type: Exception

Message: Session: Configured save path '/opt/lampp/htdocs/Mini-Inventory-and-Sales-Management-System/system/sessions' is not writable by the PHP process.

Filename: /opt/lampp/htdocs/Mini-Inventory-and-Sales-Management-System/system/libraries/Session/drivers/Session_files_driver.php

Line Number: 143

Backtrace:

File: /opt/lampp/htdocs/Mini-Inventory-and-Sales-Management-System/application/controllers/Home.php
Line: 13
Function: __construct

File: /opt/lampp/htdocs/Mini-Inventory-and-Sales-Management-System/index.php
Line: 315
Function: require_once`
![screenshot at 2018-12-08 15-20-26](https://user-images.githubusercontent.com/13417956/49685883-24733500-fafd-11e8-9009-74402235fc14.png)

**Comment by uhexos** [comment]
you need to give the others group write access from terminal. I also noticed that you have to change the name of the folder to all lowercase if not the site breaks. 

i used sudo chmod -r o=
