### ISSUE TITLE
SQL injection Vulnerability at latr_/?orderBy=transId

### ISSUE THREAD

**Issue by lawrenceamer** [amirsanni/Mini-Inventory-and-Sales-Management-System#60]
the module in line [Transaction ] line 60 is vulnerable to SQL injection . 
the vulnerable end point is latr_/?orderBy=transId' 
order by input is being sent with out escape the query , allows attackers to execute malicious SQL Payloads .

**Comment by amirsanni** [comment]
Thanks for bringing this to my notice. 

1. Were you able to successfully inject SQL via that?
2. I believed CodeIgniter's `get()` method will prevent the attack.

**Comment by lawrenceamer** [comment]
you passed `$orderby` input into transaction module as order by query with out escaping , could be fixed by binding , but i think will be better to re write safe one

**Comment by amirsanni** [comment]
The `TRUE` value passed to the second parameter of $this->input->get() is for XSS filtering. See image below from the documentation:

![image](https://user-images.githubusercontent.com/6107185/57290340-1ed24900-70b5-11e9-84e0-1cf0ef57cf8d.png)

**Comment by lawrenceamer** [comment]
, i think will be better to use binding to avoid SQL injection on selected module ` https://www.codeigniter.com/userguide2/database/queries.html`  , or wait my patch for that , you can close this ticket as Un resolved , thanks

**Comment by amirsanni** [comment]
That's exactly what I used in the model. Check the `getAll()` [here](https://github.com/amirsanni/Mini-Inventory-and-Sales-Management-System/blob/master/application/models/Transaction.php).

**Comment by lawrenceamer** [comment]
try this on your browser locally with Mysql Databases , `http://demo.com/transactions/latr_/?orderBy=transId%27&orderFormat=DESC&limit=10`
