### ISSUE TITLE
Incorrect Password

### ISSUE THREAD

**Issue by toliano** [amirsanni/Mini-Inventory-and-Sales-Management-System#62]
the demopass is not going through as the password after a successful installation on my WAMP server

**Comment by amirsanni** [comment]
This is most likely a configuration issue. Did you follow the steps in the readme? I will be able to offer advice or help if I fully understand how your environment is setup.

**Comment by toliano** [comment]
@amirsanni, thanks a lot I just found the README file and everything is working perfectly fine now. Many Thanks for your quick response.
