### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by InocencioC** [amirsanni/Mini-Inventory-and-Sales-Management-System#65]
error when I try to log in to the system:      Log in failed. Please check your internet connection and try again later.

**Comment by jy-zheng** [comment]
i am getting the same error. I tried to catch the error in /public/js/main.js handleLogin function, the error message shows The requested URL /access/login was not found on this server.

**Comment by amirsanni** [comment]
Hi, I'll update the error message to make it more descriptive.

You're getting this error due some mistakes in your configurations. Check the range and ensure you update the following files accordingly .htaccess, config.php and main.js.

**Comment by OutsidersGaming2014** [comment]
@amirsanni I have manually added my own admin user through a MySQL database, have it all connected, have set the paths as instructed, and when I try to log in each time, it says my password and email combination is incorrect.

**Comment by amirsanni** [comment]
> Hi, I'll update the error message to make it more descriptive.
> 
> You're getting this error due some mistakes in your configurations. Check the range and ensure you update the following files accordingly .htaccess, config.php and main.js.

Done.
