### ISSUE TITLE
transaction

### ISSUE THREAD

**Issue by onlinesaleem** [amirsanni/Mini-Inventory-and-Sales-Management-System#66]
at the moment of confirm order i am getting this error "Oops! Bug? Unable to process your request. Please try again or report error" but transaction saved

**Comment by amirsanni** [comment]
Is this on the demo site or your localhost?

**Comment by onlinesaleem** [comment]
> Is this on the demo site or your localhost?

after published from my localhost

**Comment by amirsanni** [comment]
Check the __application/logs__ folder to check the error message.

**Comment by onlinesaleem** [comment]
application/logs folder doesnt get any error message except index  files, showing the same error message though records saved some where i am missing help me bro.
Its nice software

![Error1](https://user-images.githubusercontent.com/8750199/74164771-44d4dd00-4c35-11ea-8d2a-aed95a49625e.JPG)
![Error2](https://user-images.githubusercontent.com/8750199/74164796-4ef6db80-4c35-11ea-89e7-4bbc5d420ac2.JPG)

**Comment by amirsanni** [comment]
Ok.

Check your browser console for errors and share if there's any.

**Comment by onlinesaleem** [comment]
failed to load resource: the server responded with a status of 500 (Internal Server Error)

![Error3](https://user-images.githubusercontent.com/8750199/74165134-b4e36300-4c35-11ea-8359-82afbe1d7370.JPG)

**Comment by amirsanni** [comment]
Let me see if I can reproduce the error from my end.

Please share the network response too. Seems to be a database query issue.

**Comment by onlinesaleem** [comment]
i am using xamp combine with apache and mysql

**Comment by amirsanni** [comment]
Check your browser network tab and share the response from the server after a new transaction.

**Comment by onlinesaleem** [comment]
Here the details you asked

![Error4](https://user-images.githubusercontent.com/8750199/74171528-c598d680-4c3f-11ea-80aa-9d38c29f2d21.JPG)

**Comment by amirsanni** [comment]
No that's not it. Let me see if I can recreate the error, if not we may need to have a remote session.

**Comment by onlinesaleem** [comment]
sure will do

**Comment by onlinesaleem** [comment]
Hi any solutions ????????????

**Comment by onlinesaleem** [comment]
Hi , now i am got the error logs please refer below those logs

<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2020-02-11 14:09:05 --> Query error: FUNCTION 1410inventory.ANY_VALUE does not exist - Invalid query: SELECT ANY_VALUE(totalMoneySpent) AS totalMoneySpent FROM transactions WHERE DATE(transDate) = CURRENT_DATE GROUP BY ref
ERROR - 2020-02-11 14:15:22 --> Query error: FUNCTION 1410inventory.ANY_VALUE does not exist - Invalid query: SELECT ANY_VALUE(totalMoneySpent) AS totalMoneySpent FROM transactions WHERE DATE(transDate) = CURRENT_DATE GROUP BY ref
ERROR - 2020-02-11 14:15:22 --> Query error: FUNCTION 1410inventory.ANY_VALUE does not exist - Invalid query: SELECT ANY_VALUE(modeOfPayment) as modeOfPayment
FROM `transactions`
WHERE YEAR(transDate) = '2020'
GROUP BY `ref`
ERROR - 2020-02-11 14:15:30 --> Query error: FUNCTION 1410inventory.ANY_VALUE does not exist - Invalid query: SELECT ANY_VALUE(transId) AS transId, ANY_VALUE(totalPrice) AS totalPrice, `transactions`.`ref`, ANY_VALUE(transactions.totalMoneySpent) AS totalMoneySpent, ANY_VALUE(transactions.modeOfPayment) AS modeOfPayment, ANY_VALUE(transactions.staffId) AS staffId, ANY_VALUE(transactions.transDate) AS transDate, ANY_VALUE(transactions.lastUpdated) AS lastUpdated, ANY_VALUE(transactions.amountTendered) AS amountTendered, ANY_VALUE(transactions.changeDue) AS changeDue, CONCAT_WS(" ", ANY_VALUE(admin.first_name), ANY_VALUE(admin.last_name)) as "staffName", ANY_VALUE(transactions.cust_name) AS cust_name, ANY_VALUE(transactions.cust_phone) AS cust_phone, ANY_VALUE(transactions.cust_email) AS cust_email, SUM(`transactions`.`quantity`) AS `quantity`
FROM `transactions`
LEFT JOIN `admin` ON `transactions`.`staffId` = `admin`.`id`
GROUP BY `ref`
ORDER BY `transId` DESC
 LIMIT 10
ERROR - 2020-02-11 14:15:30 --> Query error: FUNCTION 1410inventory.ANY_VALUE does not exist - Invalid query: SELECT ANY_VALUE(totalMoneySpent) AS totalMoneySpent FROM transactions WHERE DATE(transDate) = CURRENT_DATE GROUP BY ref
ERROR - 2020-02-11 14:15:49 --> Query error: FUNCTION 1410inventory.ANY_VALUE does not exist - Invalid query: SELECT ANY_VALUE(totalMoneySpent) AS totalMoneySpent FROM transactions WHERE DATE(transDate) = CURRENT_DATE GROUP BY ref

**Comment by amirsanni** [comment]
Oh! ANY_VALUE is not supported by mariadb. I fixed this in my last commit. Pull that and try again.

**Comment by onlinesaleem** [comment]
i changed database now its working ,thank you

**Comment by amirsanni** [comment]
Good.

Welcome.
