### ISSUE TITLE
What's the reason of this problem?

### ISSUE THREAD

**Issue by flyingtango** [amirsanni/Mini-Inventory-and-Sales-Management-System#7]
<img width="629" alt="screen shot 2017-04-17 at 21 11 14" src="https://cloud.githubusercontent.com/assets/16619555/25089812/7c79e29a-23b2-11e7-9ba9-5f7ebdc6db9f.png">

**Comment by flyingtango** [comment]
<img width="1270" alt="screen shot 2017-04-17 at 21 27 33" src="https://cloud.githubusercontent.com/assets/16619555/25090247/ba05564c-23b4-11e7-91f8-3d17b013196a.png">

**Comment by amirsanni** [comment]
@flyingtango That should as a result of your hostname (localhost:8405) having port number, I guess. Did a fix for that. Try again with the latest commit.
