### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by johnny-xcode** [amirsanni/Mini-Inventory-and-Sales-Management-System#72]
Log in failed. Please check your internet connection and try again later. I think there is a problem on the javascript. 

Please help me. Thank you

**Comment by amirsanni** [comment]
I think it's more of a wrong configuration. Ensure you set the correct path (main.js and config.js), then try again. Also, share what error you have in your browser console for context.

**Comment by johnny-xcode** [comment]
I just redownload and set again the configuration, and now it is working. 

Thank you.
