### ISSUE TITLE
Demo login credentials is not work.

### ISSUE THREAD

**Issue by dilipprajapati** [amirsanni/Mini-Inventory-and-Sales-Management-System#77]
I download the code and configure all settings but still, a 404 error shows any redirect URL.

demo not working.
https://ibb.co/ZMqs2Qr

demo not work every time showing a 404 error.
https://www.loom.com/share/e32b353b1f4e49f09f37ba6a1d13b9aa
Please give the solution.

**Comment by amirsanni** [comment]
There is an issue on the demo server. I am currently working on resolving this.

**Comment by amirsanni** [comment]
Please try now.
