### ISSUE TITLE
demo password

### ISSUE THREAD

**Issue by WWE-Corey** [amirsanni/Mini-Inventory-and-Sales-Management-System#78]
Hello - I was wanting to test the demo but neither old/new versions are not accepting 'demopass' as password.

**Comment by amirsanni** [comment]
Hi, I was able to log in just now using the same credentials.

**Comment by ph4t0o0o0om** [comment]
hi @amirsanni what demo password did you use?

**Comment by amirsanni** [comment]
Username - demo@1410inc.xyz
Password - demopass

@ph4t0o0o0om

**Comment by ph4t0o0o0om** [comment]
Hi sir @amirsanni thank you for response . this is working on v1 but on v2 not working sir. The code of v2 sir is it available?

**Comment by amirsanni** [comment]
For v2, you can sign up to test. People keep messing with the test account.

**Comment by ph4t0o0o0om** [comment]
@amirsanni yes sir I already registered and login but the system don't have any data and there is no import feature sir.

**Comment by amirsanni** [comment]
No import feature in version 2 yet.

**Comment by ph4t0o0o0om** [comment]
Noted thank you
