### ISSUE TITLE
how to see/print barcode from items code

### ISSUE THREAD

**Issue by ada12345678** [amirsanni/Mini-Inventory-and-Sales-Management-System#79]
how to see/print barcode from items code

**Comment by ph4t0o0o0om** [comment]
@ada12345678  hi did you already installed the v1? how do you import items? and what credential you use on login?

**Comment by amirsanni** [comment]
@ada12345678 i don't really understand your question but to scan a barcode, you'll need to connect a barcode scanner to your computer, and click on **scan barcode** button before scanning them item.
