### ISSUE TITLE
Log in problem

### ISSUE THREAD

**Issue by paulaneri** [amirsanni/Mini-Inventory-and-Sales-Management-System#8]
Hi!
I have a problem with Log in. Send me a message "Invalid email/password combination", but the user and pass are correct.
Thanks!

**Comment by amirsanni** [comment]
@paulaneri On your local PC or online?

**Comment by paulaneri** [comment]
Online

**Comment by paulaneri** [comment]
Here is the problem: http://usinadeideas.com.ar/test/
User: demo@1410inc.xyz
pass: demo

![screen shot 2017-06-23 at 12 56 25 pm](https://user-images.githubusercontent.com/5561497/27491319-496f5cf0-5818-11e7-957e-5cc0865b5933.png)

**Comment by amirsanni** [comment]
It won't work as the password was hard coded. The password is meant to be encrypted. I'll suggest you use the database in the source code, log in and then create new users.
