### ISSUE TITLE
Credential problem on localhost

### ISSUE THREAD

**Issue by ph4t0o0o0om** [amirsanni/Mini-Inventory-and-Sales-Management-System#80]
Hi sir @amirsanni thank you for sharing this awesome repo.  I successfully download the repo and imported the database , place the folder to hdtdocs now I just want to ask sir if the default credential on the repo is email:demo@1410inc.xyz password: demopass . Pls help

**Comment by amirsanni** [comment]
Use the signup feature to create an account.

**Comment by ph4t0o0o0om** [comment]
Hi sir @amirsanni there is no sign up feature in v1. I tried to create a account on database but it doesn't work and the error in the login page is "200 OK" . pls help I really like your work.

**Comment by amirsanni** [comment]
I thought you were referring to version 2. The username is **demo@1410inc.xyz** and password is **demopass**.

**Comment by ph4t0o0o0om** [comment]
Hi sir @amirsanni I tried that as well but I can't login the error is still "200 OK" and "Invalid email and password combination" . I believe there is a bug on the repo because when I failed to login and if I refresh the page it will redirect me inside the system but I can't change nothing . When Im inside the system I tried to create a admin the "Processing" is too long I wait for almost 30 mins but no luck.

**Comment by amirsanni** [comment]
This was fixed months ago. Sorry.
