### ISSUE TITLE
💥 Potential security vulnerability

### ISSUE THREAD

**Issue by ranjit-git** [amirsanni/Mini-Inventory-and-Sales-Management-System#83]
Potential security vulnerability has been disclosed for this repo.
You shoud have received report link to view the details in your mail amirsanni@gmail.com.
Plz check the report and if its valid then plz mark them valid there.
https://huntr.dev/bounties/1c8fedde-8045-464c-81bf-498f08b37d22/
https://huntr.dev/bounties/d36de6b4-ba4a-4315-9e79-fce38fed9afb/
https://huntr.dev/bounties/34260861-07a0-4dfe-bd24-e3f25a5c654f/
https://huntr.dev/bounties/846f3865-947f-4037-a0af-a13a366e0557/

**Comment by ranjit-git** [comment]
hello, bug is remain unfixed

**Comment by amirsanni** [comment]
Fixed https://github.com/amirsanni/Mini-Inventory-and-Sales-Management-System/commit/ba36f600b021f45104a17caa6e78a23dd3b05e19
